/*
    Highly divisible triangular number
    Sequence of triangle numbers is generated by adding the natural numbers.
    7th triangle number : 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. 
    The first ten terms would be: 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
    Factors of the first seven triangle numbers:
    1: 1
    3: 1, 3
    6: 1, 2, 3, 6
    10: 1, 2, 5, 10
    15: 1, 3, 5, 15
    21: 1, 3, 7, 21
    28: 1, 2, 4, 7, 14, 28
    We can see that 28 is the first triangle number to have over five divisors.

    What is the value of the first triangle number to have over n divisors?
*/
import java.io.*;
class Problem12{
    int getNumberFactor(long num){
        int count =1;
        if( num == 1)return count;
        for(long i=2;i*i<= num; i++){
            if(num%i ==0){
                count++;
                if(num / i != i)count++;
            }

        }
        count++;
        return count;
    }
    long divisibleTriangularNumber(int num){
        int sum = 0;
        for(int i=1;;i++){
            sum += i;
            int fact = getNumberFactor(sum);
            if(fact>num)
                return sum;
        }
    }
    public static void main(String args[])throws IOException{
        BufferedReader br=new BufferedReader(new InputStreamReader(System.in));
        Problem12 obj=new Problem12();
        int t = Integer.parseInt(br.readLine());
        while(t-->0){
            int number = Integer.parseInt(br.readLine());
            System.out.println(obj.divisibleTriangularNumber(number));
        }
    }
}

/*
    Output:
    >javac Problem12.java
    >java Problem12
    >5
    >5
    28
    >23
    630
    >167
    1385280
    >374
    17907120
    >500
    76576500
*/